
### Registration endpoint
POST  http://localhost:5400/api/auth/register
content-type: application/json 

{
    "username":"user4",
    "password": "1234",
    "email": "gg@g5mail.com"
}

### Login enpoint
POST  http://localhost:5400/api/auth/login
content-type: application/json 

{
    "username":"user2",
    "password": "1234"
}