

GET http://localhost:5400/api/shoes


### Authentication
POST http://localhost:5400/api/auth/login 
content-type: application/json

{
    "username": "katleho",
    "password": "1234"
}


### Get User Cart
GET http://localhost:5400/api/cart 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGxlaG8iLCJhZG1pblVzZXIiOmZhbHNlLCJpYXQiOjE2OTY5MjY1Nzh9.1UZNx3C0QlxCJk6ey3Tj5mzrbFWEXOKEzO-WPi_tmII 


### Add to cart
POST http://localhost:5400/api/cart/add-to-cart/46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGxlaG8iLCJhZG1pblVzZXIiOmZhbHNlLCJpYXQiOjE2OTY5MjY1Nzh9.1UZNx3C0QlxCJk6ey3Tj5mzrbFWEXOKEzO-WPi_tmII 

