### Gets all routes
GET http://localhost:5400/


### Gets all shoes
GET http://localhost:5400/api/shoes


### Filters by brand
GET http://localhost:5400/api/shoes/brand/Gucci


### Filters by color
GET http://localhost:5400/api/shoes/color/red


### Filters by size
GET http://localhost:5400/api/shoes/size/6


### Filters by brand and size
GET http://localhost:5400/api/shoes/brand/Gucci/size/7


### Filters by size and color
GET http://localhost:5400/api/shoes/size/7/color/black


### Filters by brand and color
GET http://localhost:5400/api/shoes/brand/Gucci/color/black

###  Filters by brand, size and color
GET http://localhost:5400/api/shoes/brand/Gucci/size/7/color/black


### adds a new shoe
POST http://localhost:5400/api/shoes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW5Vc2VyIjp0cnVlLCJpYXQiOjE2OTYwODIzNTh9.iaULFASfYLksmWjHlyCjTflgfa76HpbjzwjoHrQVz8Q
content-type: application/json 

{
    "shoe_name": "Men’s Game Advance",
    "brand": "Lacoste",
    "size": "8",
    "price": "2685",
    "image_url": "https://image1.lacoste.com/dw/image/v2/AAQM_PRD/on/demandware.static/Sites-ZA-Site/Sites-master/en_ZA/dw14a5f9be/41SMA0015_65T_01.jpg",
    "color": "white",
    "stock_quantity": 14,
    "description": "This is a detailed description of the shoe"

}

###
POST http://localhost:5400/api/shoes/sold/2
content-type: application/json 

{
    "quantity": 2
}
