
GET http://localhost:5400/api/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjk1MTc2MzQwfQ.TTwBtRTIbG-om9Uibzf1MHILiOYYoJxaC_GWLvWMedo 


### ADDS Shoes To Cart
POST http://localhost:5400/api/cart/add-to-cart/2


### Remove Shoe From Cart
POST http://localhost:5400/api/cart/remove-from-cart/2