### Gets all routes
GET http://localhost:3000/


### Gets all shoes
GET http://localhost:3000/api/shoes


### Filters by brand
GET http://localhost:3000/api/shoes/brand/Gucci


### Filters by color
GET http://localhost:3000/api/shoes/color/red


### Filters by size
GET http://localhost:3000/api/shoes/size/6


### Filters by brand and size
GET http://localhost:3000/api/shoes/brand/Gucci/size/7


### Filters by size and color
GET http://localhost:3000/api/shoes/size/7/color/black


### Filters by brand and color
GET http://localhost:3000/api/shoes/brand/Gucci/color/black

###  Filters by brand, size and color
GET http://localhost:3000/api/shoes/brand/Gucci/size/7/color/black


### adds a new shoe
POST http://localhost:3000/api/shoes
content-type: application/json 

{
    "shoe_name": "Balenciaga Track Sneaker 2",
    "brand": "Balenciaga",
    "size": "8",
    "price": "9500",
    "image_url": "https://i.ebayimg.com/00/s/MTYwMFgxNjAw/z/MUQAAOSwQ1Fjfq8z/$_57.JPG?set_id=880000500F",
    "color": "gray",
    "quantity": 14

}


###

POST http://localhost:3000/api/shoes/sold/2
content-type: application/json 

{
    "quantity": 2
}
